---
kind: pipeline
type: docker
name: default

steps:
  - name: lint
    image: golangci/golangci-lint:v1.34
    commands:
      - go mod download
      - golangci-lint run -v --timeout 10m
    environment:
      GOPROXY: http://goproxy
  - name: build
    image: golang:1.15.8-alpine3.13
    commands:
      - apk add --no-cache ca-certificates build-base
      - wget https://github.com/CosmWasm/wasmvm/releases/download/v0.13.0/libwasmvm_muslc.a -O /lib/libwasmvm_muslc.a
      - make install-pkger
      - make build-alpine
    environment:
      GOPROXY: http://goproxy
  - name: publish-docker
    image: plugins/docker:18
    settings:
      dockerfile: Dockerfile
      repo: publicawesome/stakewatcher
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch: 
        - master
      event:
        - push
  - name: discord
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: discord_webhook_id
      webhook_token:
        from_secret: discord_webhook_token
    when:
      status: [success, failure]
---
kind: signature
hmac: 3221404ed531743db2f2a559ff7aff8f0c57590fbbcc6422f9457d90c1d088ec

...
