---
kind: pipeline
type: docker
name: default

steps:
  - name: lint
    image: golangci/golangci-lint:v1.29
    commands:
      - go mod download
      - golangci-lint run -v --timeout 3m
    environment:
      GOPROXY: http://goproxy
  - name: build
    image: golang:1.14.6
    commands:
      - apt-get update && apt-get install cmake -y
      - make install-pkger
      - make build-linux
    environment:
      GOPROXY: http://goproxy
  - name: publish-docker
    image: plugins/docker:18
    settings:
      dockerfile: Dockerfile
      repo: publicawesome/stakewatcher
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch: master
      event:
        - push
  - name: slack
    image: plugins/slack
    settings:
      webhook:
        from_secret: slack_webhook
    when:
      status: [success, failure]

---
kind: signature
hmac: 9439a1bdae4a43f6ff52d2af4ddb1ab441660e9a3c25b70fadec460801795e32

...
