---
kind: pipeline
type: docker
name: default

steps:
  - name: lint
    image: golangci/golangci-lint:v1.34
    commands:
      - go mod download
      - golangci-lint run -v --timeout 5m
    environment:
      GOPROXY: http://goproxy
  - name: build
    image: golang:1.15.8-alpine3.13
    commands:
      - apt-get update && apt-get install cmake -y
      - make install-pkger
      - make build-linux
    environment:
      GOPROXY: http://goproxy
  - name: publish-docker
    image: plugins/docker:18
    settings:
      dockerfile: Dockerfile
      repo: publicawesome/stakewatcher
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch: 
        - master
        - shanev/update-stargaze-build
      event:
        - push
  - name: discord
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: discord_webhook_id
      webhook_token:
        from_secret: discord_webhook_token
    when:
      status: [success, failure]
---
kind: signature
hmac: 7ceb1926685141ac708136d5e8ea70217408c73b97d67b569cfba42454f05789

...
