---
kind: pipeline
type: docker
name: default

steps:
  - name: lint
    image: golangci/golangci-lint:v1.34
    commands:
      - go mod download
      - golangci-lint run -v --timeout 5m
    environment:
      GOPROXY: http://goproxy
  - name: build
    image: golang:1.15.7
    commands:
      - apt-get update && apt-get install cmake -y
      - make install-pkger
      - make build-linux
    environment:
      GOPROXY: http://goproxy
  - name: publish-docker
    image: plugins/docker:18
    settings:
      dockerfile: Dockerfile
      repo: publicawesome/stakewatcher
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
    when:
      branch: master
      event:
        - push
  - name: discord
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: discord_webhook_id
      webhook_token:
        from_secret: discord_webhook_token
    when:
      status: [success, failure]
---
kind: signature
hmac: e9a9dbb9c74295299555b01a06caa15c3f53c83cc6e210521c04907fab6a8bc8

...
