version: '3.7'

services:
  db:
    image: postgres:12.2
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: stargazer
    volumes:
      - db:/var/lib/postgresql/data
  adminer:
    image: adminer
    ports:
      - 9090:8080
volumes:
  db: {}
